### PR TITLE
Cherry-pick upstream PR 1407: Add joint velocity limit constraint support

### LINKED ISSUE #17: Cherry-pick dart PR 1407
https://github.com/dartsim/dart/pull/1407

Without this PR, it seems that [`<joint><axis><limit><velocity>`](http://sdformat.org/spec?ver=1.6&elem=joint#limit_velocity) is ignored, although the parsed data are passed to DART:

https://github.com/ignitionrobotics/ign-physics/blob/56a04fe204afa77e6a16d84b27ec289823eb330a/dartsim/src/SDFFeatures.cc#L116-L134

So creating a JointPositionController in ign-gazebo creates unusable controllers, as they use unlimited velocity if enough force is allowed (yes, if the joint was modeled super precisely, including all daping/internal friction etc., this artificial limit would not be needed, but being able to set this limit simplifies the creation of models a lot).

This did not show in any of ign-gazebo tests as none of them actually set the velocity limits and check them.

### PR DESCRIPTION
**Pull request by scpeters**
This is a cherry-pick of https://github.com/dartsim/dart/pull/1407 that will fix #17.

### CODE REVIEW

**Comment by peci1** [comment]
Thanks for the super-fast reaction :+1: 

Just looking at the diff in changelog, it seems it has picked up some unrelated changes... Other files seem fine.

**Review by azeey — COMMENTED** [review]
There are some test failures. I think we also need https://github.com/dartsim/dart/pull/1371? Otherwise, looks good to me.

**Comment by scpeters** [comment]
> There are some test failures. I think we also need [dartsim#1371](https://github.com/dartsim/dart/pull/1371)? Otherwise, looks good to me.

I just cherry-picked this

**Comment by scpeters** [comment]
@azeey the actions fail when building tutorials. have you seen this before?

**Comment by azeey** [comment]
> @azeey the actions fail when building tutorials. have you seen this before?

I have not. I believe the Github action was added in https://github.com/ignition-forks/dart/pull/13 and it looks like those jobs failed too, although, I can't tell if they failed for the same reason. The logs are not available anymore.

**Comment by scpeters** [comment]
> > @azeey the actions fail when building tutorials. have you seen this before?
> 
> I have not. I believe the Github action was added in #13 and it looks like those jobs failed too, although, I can't tell if they failed for the same reason. The logs are not available anymore.

should we try to fix the action or review with manual testing?

**Comment by azeey** [comment]
Removing `dart/gui/osg/render/render.hpp` and `dart/gui/osg/osg.hpp` from the source fixes the build for me. They were introduced in #16. It looks like there are `render.hpp.in` and `osg.hpp.in` that CMake uses to generate these files and right now, the generated files recursively include themselves. Here's an the generated `render.hpp`:

```
#include "dart/gui/osg/render/BoxShapeNode.hpp"
#include "dart/gui/osg/render/CapsuleShapeNode.hpp"
#include "dart/gui/osg/render/ConeShapeNode.hpp"
#include "dart/gui/osg/render/CylinderShapeNode.hpp"
#include "dart/gui/osg/render/EllipsoidShapeNode.hpp"
#include "dart/gui/osg/render/HeightmapShapeNode.hpp"
#include "dart/gui/osg/render/LineSegmentShapeNode.hpp"
#include "dart/gui/osg/render/MeshShapeNode.hpp"
#include "dart/gui/osg/render/MultiSphereShapeNode.hpp"
#include "dart/gui/osg/render/PlaneShapeNode.hpp"
#include "dart/gui/osg/render/PointCloudShapeNode.hpp"
#include "dart/gui/osg/render/ShapeNode.hpp"
#include "dart/gui/osg/render/SoftMeshShapeNode.hpp"
#include "dart/gui/osg/render/SphereShapeNode.hpp"
#include "dart/gui/osg/render/VoxelGridShapeNode.hpp"
#include "dart/gui/osg/render/WarningShapeNode.hpp"
#include "dart/gui/osg/render/render.hpp"
```
Note the last line will end up including itself.

/CC @mjcarroll

**Comment by scpeters** [comment]
> Removing `dart/gui/osg/render/render.hpp` and `dart/gui/osg/osg.hpp` from the source fixes the build for me. They were introduced in #16. It looks like there are `render.hpp.in` and `osg.hpp.in` that CMake uses to generate these files and right now, the generated files recursively include themselves. Here's an the generated `render.hpp`:
> 
> ```
> #include "dart/gui/osg/render/BoxShapeNode.hpp"
> #include "dart/gui/osg/render/CapsuleShapeNode.hpp"
> #include "dart/gui/osg/render/ConeShapeNode.hpp"
> #include "dart/gui/osg/render/CylinderShapeNode.hpp"
> #include "dart/gui/osg/render/EllipsoidShapeNode.hpp"
> #include "dart/gui/osg/render/HeightmapShapeNode.hpp"
> #include "dart/gui/osg/render/LineSegmentShapeNode.hpp"
> #include "dart/gui/osg/render/MeshShapeNode.hpp"
> #include "dart/gui/osg/render/MultiSphereShapeNode.hpp"
> #include "dart/gui/osg/render/PlaneShapeNode.hpp"
> #include "dart/gui/osg/render/PointCloudShapeNode.hpp"
> #include "dart/gui/osg/render/ShapeNode.hpp"
> #include "dart/gui/osg/render/SoftMeshShapeNode.hpp"
> #include "dart/gui/osg/render/SphereShapeNode.hpp"
> #include "dart/gui/osg/render/VoxelGridShapeNode.hpp"
> #include "dart/gui/osg/render/WarningShapeNode.hpp"
> #include "dart/gui/osg/render/render.hpp"
> ```
> 
> Note the last line will end up including itself.
> 
> /CC @mjcarroll

sounds like the headers need `#pragma once` or header guards

**Comment by scpeters** [comment]
I made a clean PR to remove `osg.hpp` and `render.hpp` in https://github.com/ignition-forks/dart/pull/24, but CI is still failing, maybe related to octomap?

**Comment by scpeters** [comment]
I just rebased on top of `release-6.10`

**Comment by scpeters** [comment]
@azeey I think this just has the known failing test

**Review by azeey — APPROVED** [review]
I have manually tested all the SubT models that have velocity limits. Most of them are not affected by this PR because they use Servo mode for joint velocity commands, which complied with the velocity limits already. This PR affects joints controlled in force mode. And for SubT models that use joint controllers in force mode, I did not observe any noticeable difference.

**Pull request merged**
