### PR TITLE
Remove osg.hpp, render.hpp to fix CI

### PR DESCRIPTION
**Pull request by scpeters**
These header files are auto-generated by cmake and were
added for bazel support, but they break cmake when present
due to a lack of header guards or a pragma once.

***

**Before creating a pull request**

- [X] Document new methods and classes
- [X] Format new code files using `clang-format`

**Before merging a pull request**

- [ ] Set version target by selecting a milestone on the right side
- [ ] Summarize this change in `CHANGELOG.md`
- [ ] Add unit test(s) for this change

### CODE REVIEW

**Comment by peci1** [comment]
If there are problems regarding octomap, can it be related to https://github.com/ros/rosdistro/issues/26527 ? It explicitly mentions DART as one of the affected packages.

**Comment by peci1** [comment]
Ahh, my bad, that one's for Noetic. However, couldn't the reasoning be similar? Also, the CI is running on Ubuntu 16.04 (if you're talking about the Github Actions CI).

**Review by mjcarroll — APPROVED** [review]

**Comment by azeey** [comment]
I removed `config.hpp` in 37420ba. That fixed the build for me locally.

**Review by azeey — APPROVED** [review]
Now CI is failing only because of a known test failure. @mjcarroll , does removing `config.hpp` break Bazel builds?

**Comment by mjcarroll** [comment]
> Now CI is failing only because of a known test failure. @mjcarroll , does removing config.hpp break Bazel builds?

It will temporarily, I'm going to fix it in a follow-up PR.  Feel free to merge this to get CI turning again.

**Comment by mjcarroll** [comment]
The follow up fix to this is in #25

**Pull request merged**
